management:
    port: 8081

server:
    port: 8000
    error:
        path: /error
        whitelabel:
            enabled: true
    
info:
    app:
        name: Lego
        description: ${info.app.name} that searches the Legal Departments document repository (Legal Ethics Governance Office)
    build:
        name: lego
        version: 0.0.1
      
endpoints:
    beans:
        id: lego
    shutdown:
        enabled: true
    health:
        sensitive: true
        
---

spring:
    resources:
        chain:
            strategy:
                content:
                    enabled: true
                    paths: /**
                    
---                    
    
spring:
    application.name: Lego
    profiles.active: dev
    
---

spring:
  profiles: production
  name: Production Server
  url: http://production
  collection: lego
---

spring:
  profiles: dev
  name: Development Server
  url: http://dev
  collection: lego

