environments:
    collections: 
      - lego
      - legoDev
    
    servers:
      - http://web-solrcloudspardev-01.internal.sanger.ac.uk:8080/
      - http://web-solrcloudsparlive-01.internal.sanger.ac.uk:8000/

management:
    port: 8081

server:
    port: 8080

info:
    app:
        name: Lego Service
        description: ${info.app.name} that searches the Legal Departments document repository
    build:
        name: lego
        version: 0.0.1
      
endpoints:
    beans:
        id: lego
    shutdown:
        enabled: true
    health:
        sensitive: true
        
---

spring:
    application.name: Lego
    profiles.active: production
    
---

spring:
  profiles: production
  name: Production Server
  url: http://production
---

spring:
  profiles: dev
  name: Development Server
  url: http://dev

  
